### PR TITLE
Converted transitions to CSS

### PR DESCRIPTION
**Pull request by MichaelArestad**
- Transforms should perform better in low-memory environments
- CSS relies on a class on the body

### CODE REVIEW

**Comment by markjaquith** [comment]
This is behaving very oddly on Chrome, doesn't work in Safari, and has a bunch of other changes.

Chrome (what the heck!?):

screen shot 2014-10-28 at 11 07 06 am

**Comment by michaelbeil** [comment]
Chrome and Firefox work well with this PR, but Safari is being a bother for me.

**Comment by MichaelArestad** [comment]
Whoa. Looking into this.

**Comment by MichaelArestad** [comment]
Added `transform: translateZ(0);` to `.quicklinks` on the admin bar. This fixed the repaint issues I can reproduce, but you'll need to test on your computer.

**Comment by ellatrix** [comment]
Weird, GitHub didn't fix this automatically.

**Pull request closed without merging**
